#!/usr/bin/env bash
set -euax

PATH=$PATH:/home/Jack.Woollen/bin:.

export inst=ascatw 
export bird=$1
export year=$2
export yend=$2
export root=$(cd ..; pwd)
export bush=$root/ush  
export exec=$root/exec
export fixt=$root/fix
export data=$ptmp/ascat25/data  
export here=$ptmp/ascat25/here; mkdir -p $here

[[ $# -eq 3 ]] && mnths="$3" || mnths="01 02 03 04 05 06 07 08 09 10 11 12"

while [[ $year -le $yend ]]; do
for mnth in $mnths; do
cd $here; work=$PWD/work.$mnth; cd $work
echo $(date) creating $here/$inst.$bird.$year$mnth

yrmn=$year$mnth
ymdf=${yrmn}01
yrml=$(bumpidx $yrmn -1)
ymdl=$(bumpidx $ymdf -1)

set +e; tar --wildcards -xf $data/ASCAT25*$yrml OR1ASW025_$ymdl\* >/dev/null 2>&1
set -e; tar --wildcards -xf $data/ASCAT25*$yrmn OR1ASW025_${yrmn}\*

cat OR1ASW025* > $bird.$yrmn.cat

mkdir -p synoptic; cd synoptic

ln -sf $work/$bird.$year$mnth.cat   fort.20
ln -sf $fixt/$inst.tab             fort.21
ln -sf $fixt/$inst.tab             fort.50
#echo $inst.$bird|$exec/convert.x ##>/dev/null

mkdir -p prepro; cd prepro

for ascin in $(ls ../$inst.$bird.$yrmn*); do
$bush/prepro_ascatw $ascin $(basename $ascin) >/dev/null
done

tar -cf $here/$inst.$bird.$year$mnth  $inst.$bird.$yrmn*

rm -rf $work

done # months
year=$((year+1))
done #years
