#!/usr/bin/env bash
set -eua

#  define the process infrastructure
#  ---------------------------------

export yrmn=$1
export inst=ascatw
export root=$(cd ..; pwd)
export bush=$root/ush  
export exec=$root/exec
export fixt=$root/fix
export year=$(echo $yrmn|cut -c 1-4)
export data=$ptmp/prepsfcw.$year

#  set up the working area
#  -----------------------

work=$data/work.$inst.$yrmn; rm -rf $work; mkdir -p $work; cd $work
echo $(date) creating $work 

prep=$data/prepdata.$yrmn; mkdir -p $prep
echo $(date) creating $prep 

#  stage the month of data to process
#  ----------------------------------

ymdf=${yrmn}01
yrml=$(bumpidx $yrmn -1)
ymdl=$(bumpidx $ymdf -1)

set +e; tar --wildcards -xf $data/ASCAT25*$yrml OR1ASW025_$ymdl\* >/dev/null 2>&1
set -e; tar --wildcards -xf $data/ASCAT25*$yrmn OR1ASW025_${yrmn}\*

cat OR1ASW025* > OR1ASW025.$yrmn.cat

#  reformat and rebin the month into synoptic times
#  ------------------------------------------------

mkdir synoptic; cd synoptic

ln -sf $work/OR1ASW025.$yrmn.cat   fort.20
ln -sf $fixt/$inst.tab             fort.21
ln -sf $fixt/$inst.tab             fort.50
echo $inst.eums|$exec/convert

#  qc and superob the synoptic data
#  --------------------------------

mkdir prepro; cd prepro

for ascin in $(ls ../$inst.eums.$yrmn*); do
$bush/prepro_ascatw $ascin $(basename $ascin) >/dev/null
done

#  store the synoptic data and clean out the work directory
#  --------------------------------------------------------

cp $inst.eums.$yrmn* $prep               
##cd $data; rm -rf $work

