#!/bin/bash
set -eua

outs=$PWD/outputs; mkdir -p $outs

cat<<eof | qsub -
#PBS -N $1.$2             
#PBS -o $outs/$1.$2.$3.$$                
#PBS -l select=1:ncpus=1:mem=5GB     
#PBS -l walltime=02:00:00
#PBS -q dev
#PBS -A CFS-DEV
#PBS -j oe        
#PBS -V           

set -euax  

cd $PWD; time $*

eof

