#!/bin/bash
set -euax

outs=$PWD/outputs; mkdir -p $outs

cat<<eof | qsub -
#PBS -N $1.$2                  
#PBS -o $outs/$1.$2.$$                
#PBS -l select=1:ncpus=1:mem=5GB     
#PBS -l walltime=03:00:00
#PBS -q dev_transfer
#PBS -A CFS-DEV
#PBS -j oe        
#PBS -V           

set -euax  

set +x
module load netcdf/4.7.4
set -x

SUBDIR=$PWD; cd $PWD; time $*

eof

